name: CI

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.402

    - name: Build
      run: dotnet build --nologo

    - name: Test
      run: dotnet test --nologo MySuperService.Tests/MySuperService.Tests.csproj

    - name: Publish
      run: dotnet publish --nologo --no-build MySuperService/MySuperService.csproj

    - name: Create Zip
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r publish.zip _publish
