name: GGG

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Check dotnet
      run: dotnet --info

